server:
    port: 8081

spring:
    application:
        name: miigras-backend

    datasource:
        url: jdbc:mysql://localhost:3307/miigras_db
        username: root
        password: KhT321
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
    output:
        ansi:
            enabled: always

logging:
    file:
        name: logs/miigras-backend.log
        path: logs/miigras-backend
    exception-conversion-word:

application:
    security:
        jwt:
            secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
#            expiration: 120000
            expiration: 86400000

#    Emotion prediction model
    emotion:
        prediction:
            url: http://127.0.0.1:8000/send
